services:
  mongodb:
    image: mongo:7.0
    container_name: kahnu_mongodb_container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27018:27017
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: